# Generated by Django 4.1.1 on 2022-10-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fecha_de_inicio',
            field=models.DateField(null=True),
        ),
    ]
